name: build-and-release

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: github 
        settings-path: ${{ github.workspace }} 
          
    - name: Build with Maven
      run: mvn -B clean package 

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -B releaser:release -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}